[project]
name = 'Blockchain-Enabled-Waste-Management-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.environmental-impact]
path = 'contracts/environmental-impact.clar'
clarity_version = 2
epoch = 2.5

[contracts.recycling-reward]
path = 'contracts/recycling-reward.clar'
clarity_version = 2
epoch = 2.5

[contracts.sorting-verification]
path = 'contracts/sorting-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.waste-collection]
path = 'contracts/waste-collection.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
